// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: pkg/pb/monitor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamPacketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packets       []*Packet              `protobuf:"bytes,1,rep,name=packets,proto3" json:"packets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPacketsRequest) Reset() {
	*x = StreamPacketsRequest{}
	mi := &file_pkg_pb_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPacketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPacketsRequest) ProtoMessage() {}

func (x *StreamPacketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPacketsRequest.ProtoReflect.Descriptor instead.
func (*StreamPacketsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *StreamPacketsRequest) GetPackets() []*Packet {
	if x != nil {
		return x.Packets
	}
	return nil
}

type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *PacketMetadata        `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Layers        []*Layer               `protobuf:"bytes,2,rep,name=layers,proto3" json:"layers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_pkg_pb_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_pkg_pb_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *Packet) GetMetadata() *PacketMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Packet) GetLayers() []*Layer {
	if x != nil {
		return x.Layers
	}
	return nil
}

type PacketMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CaptureLength uint32                 `protobuf:"varint,3,opt,name=capture_length,json=captureLength,proto3" json:"capture_length,omitempty"`
	Length        uint32                 `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	InterfaceName string                 `protobuf:"bytes,5,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	Prefix        string                 `protobuf:"bytes,6,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Hook          string                 `protobuf:"bytes,7,opt,name=hook,proto3" json:"hook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketMetadata) Reset() {
	*x = PacketMetadata{}
	mi := &file_pkg_pb_monitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketMetadata) ProtoMessage() {}

func (x *PacketMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_monitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketMetadata.ProtoReflect.Descriptor instead.
func (*PacketMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_pb_monitor_proto_rawDescGZIP(), []int{2}
}

func (x *PacketMetadata) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *PacketMetadata) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PacketMetadata) GetCaptureLength() uint32 {
	if x != nil {
		return x.CaptureLength
	}
	return 0
}

func (x *PacketMetadata) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *PacketMetadata) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *PacketMetadata) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *PacketMetadata) GetHook() string {
	if x != nil {
		return x.Hook
	}
	return ""
}

type Layer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Layer:
	//
	//	*Layer_Ethernet
	//	*Layer_Ipv4
	//	*Layer_Ipv6
	//	*Layer_Tcp
	//	*Layer_Udp
	//	*Layer_Icmpv4
	//	*Layer_Icmpv6
	Layer         isLayer_Layer `protobuf_oneof:"layer"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Layer) Reset() {
	*x = Layer{}
	mi := &file_pkg_pb_monitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer) ProtoMessage() {}

func (x *Layer) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_monitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer.ProtoReflect.Descriptor instead.
func (*Layer) Descriptor() ([]byte, []int) {
	return file_pkg_pb_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *Layer) GetLayer() isLayer_Layer {
	if x != nil {
		return x.Layer
	}
	return nil
}

func (x *Layer) GetEthernet() *LayerEthernet {
	if x != nil {
		if x, ok := x.Layer.(*Layer_Ethernet); ok {
			return x.Ethernet
		}
	}
	return nil
}

func (x *Layer) GetIpv4() *LayerIPv4 {
	if x != nil {
		if x, ok := x.Layer.(*Layer_Ipv4); ok {
			return x.Ipv4
		}
	}
	return nil
}

func (x *Layer) GetIpv6() *LayerIPv6 {
	if x != nil {
		if x, ok := x.Layer.(*Layer_Ipv6); ok {
			return x.Ipv6
		}
	}
	return nil
}

func (x *Layer) GetTcp() *LayerTCP {
	if x != nil {
		if x, ok := x.Layer.(*Layer_Tcp); ok {
			return x.Tcp
		}
	}
	return nil
}

func (x *Layer) GetUdp() *LayerUDP {
	if x != nil {
		if x, ok := x.Layer.(*Layer_Udp); ok {
			return x.Udp
		}
	}
	return nil
}

func (x *Layer) GetIcmpv4() *LayerICMPV4 {
	if x != nil {
		if x, ok := x.Layer.(*Layer_Icmpv4); ok {
			return x.Icmpv4
		}
	}
	return nil
}

func (x *Layer) GetIcmpv6() *LayerICMPV6 {
	if x != nil {
		if x, ok := x.Layer.(*Layer_Icmpv6); ok {
			return x.Icmpv6
		}
	}
	return nil
}

type isLayer_Layer interface {
	isLayer_Layer()
}

type Layer_Ethernet struct {
	Ethernet *LayerEthernet `protobuf:"bytes,2,opt,name=ethernet,proto3,oneof"`
}

type Layer_Ipv4 struct {
	Ipv4 *LayerIPv4 `protobuf:"bytes,3,opt,name=ipv4,proto3,oneof"`
}

type Layer_Ipv6 struct {
	Ipv6 *LayerIPv6 `protobuf:"bytes,4,opt,name=ipv6,proto3,oneof"`
}

type Layer_Tcp struct {
	Tcp *LayerTCP `protobuf:"bytes,5,opt,name=tcp,proto3,oneof"`
}

type Layer_Udp struct {
	Udp *LayerUDP `protobuf:"bytes,6,opt,name=udp,proto3,oneof"`
}

type Layer_Icmpv4 struct {
	Icmpv4 *LayerICMPV4 `protobuf:"bytes,7,opt,name=icmpv4,proto3,oneof"`
}

type Layer_Icmpv6 struct {
	Icmpv6 *LayerICMPV6 `protobuf:"bytes,8,opt,name=icmpv6,proto3,oneof"`
}

func (*Layer_Ethernet) isLayer_Layer() {}

func (*Layer_Ipv4) isLayer_Layer() {}

func (*Layer_Ipv6) isLayer_Layer() {}

func (*Layer_Tcp) isLayer_Layer() {}

func (*Layer_Udp) isLayer_Layer() {}

func (*Layer_Icmpv4) isLayer_Layer() {}

func (*Layer_Icmpv6) isLayer_Layer() {}

type LayerEthernet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcMac        string                 `protobuf:"bytes,1,opt,name=src_mac,json=srcMac,proto3" json:"src_mac,omitempty"`
	DestMac       string                 `protobuf:"bytes,2,opt,name=dest_mac,json=destMac,proto3" json:"dest_mac,omitempty"`
	Ethertype     string                 `protobuf:"bytes,3,opt,name=ethertype,proto3" json:"ethertype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerEthernet) Reset() {
	*x = LayerEthernet{}
	mi := &file_pkg_pb_monitor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerEthernet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerEthernet) ProtoMessage() {}

func (x *LayerEthernet) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_monitor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerEthernet.ProtoReflect.Descriptor instead.
func (*LayerEthernet) Descriptor() ([]byte, []int) {
	return file_pkg_pb_monitor_proto_rawDescGZIP(), []int{4}
}

func (x *LayerEthernet) GetSrcMac() string {
	if x != nil {
		return x.SrcMac
	}
	return ""
}

func (x *LayerEthernet) GetDestMac() string {
	if x != nil {
		return x.DestMac
	}
	return ""
}

func (x *LayerEthernet) GetEthertype() string {
	if x != nil {
		return x.Ethertype
	}
	return ""
}

type LayerIPv4 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcIp         string                 `protobuf:"bytes,1,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DestIp        string                 `protobuf:"bytes,2,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Ttl           uint32                 `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerIPv4) Reset() {
	*x = LayerIPv4{}
	mi := &file_pkg_pb_monitor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerIPv4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerIPv4) ProtoMessage() {}

func (x *LayerIPv4) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_monitor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerIPv4.ProtoReflect.Descriptor instead.
func (*LayerIPv4) Descriptor() ([]byte, []int) {
	return file_pkg_pb_monitor_proto_rawDescGZIP(), []int{5}
}

func (x *LayerIPv4) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *LayerIPv4) GetDestIp() string {
	if x != nil {
		return x.DestIp
	}
	return ""
}

func (x *LayerIPv4) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *LayerIPv4) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type LayerIPv6 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcIp         string                 `protobuf:"bytes,1,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DestIp        string                 `protobuf:"bytes,2,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	NextHeader    string                 `protobuf:"bytes,3,opt,name=next_header,json=nextHeader,proto3" json:"next_header,omitempty"`
	HopLimit      uint32                 `protobuf:"varint,4,opt,name=hop_limit,json=hopLimit,proto3" json:"hop_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerIPv6) Reset() {
	*x = LayerIPv6{}
	mi := &file_pkg_pb_monitor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerIPv6) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerIPv6) ProtoMessage() {}

func (x *LayerIPv6) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_monitor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerIPv6.ProtoReflect.Descriptor instead.
func (*LayerIPv6) Descriptor() ([]byte, []int) {
	return file_pkg_pb_monitor_proto_rawDescGZIP(), []int{6}
}

func (x *LayerIPv6) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *LayerIPv6) GetDestIp() string {
	if x != nil {
		return x.DestIp
	}
	return ""
}

func (x *LayerIPv6) GetNextHeader() string {
	if x != nil {
		return x.NextHeader
	}
	return ""
}

func (x *LayerIPv6) GetHopLimit() uint32 {
	if x != nil {
		return x.HopLimit
	}
	return 0
}

type LayerTCP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcPort       uint32                 `protobuf:"varint,1,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DestPort      uint32                 `protobuf:"varint,2,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	Seq           uint32                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Ack           uint32                 `protobuf:"varint,4,opt,name=ack,proto3" json:"ack,omitempty"`
	DataOffset    uint32                 `protobuf:"varint,5,opt,name=data_offset,json=dataOffset,proto3" json:"data_offset,omitempty"`
	Window        uint32                 `protobuf:"varint,6,opt,name=window,proto3" json:"window,omitempty"`
	Checksum      uint32                 `protobuf:"varint,7,opt,name=checksum,proto3" json:"checksum,omitempty"`
	UrgentPointer uint32                 `protobuf:"varint,8,opt,name=urgent_pointer,json=urgentPointer,proto3" json:"urgent_pointer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerTCP) Reset() {
	*x = LayerTCP{}
	mi := &file_pkg_pb_monitor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerTCP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerTCP) ProtoMessage() {}

func (x *LayerTCP) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_monitor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerTCP.ProtoReflect.Descriptor instead.
func (*LayerTCP) Descriptor() ([]byte, []int) {
	return file_pkg_pb_monitor_proto_rawDescGZIP(), []int{7}
}

func (x *LayerTCP) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *LayerTCP) GetDestPort() uint32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

func (x *LayerTCP) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *LayerTCP) GetAck() uint32 {
	if x != nil {
		return x.Ack
	}
	return 0
}

func (x *LayerTCP) GetDataOffset() uint32 {
	if x != nil {
		return x.DataOffset
	}
	return 0
}

func (x *LayerTCP) GetWindow() uint32 {
	if x != nil {
		return x.Window
	}
	return 0
}

func (x *LayerTCP) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *LayerTCP) GetUrgentPointer() uint32 {
	if x != nil {
		return x.UrgentPointer
	}
	return 0
}

type LayerUDP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcPort       uint32                 `protobuf:"varint,1,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DestPort      uint32                 `protobuf:"varint,2,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	Length        uint32                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	Checksum      uint32                 `protobuf:"varint,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerUDP) Reset() {
	*x = LayerUDP{}
	mi := &file_pkg_pb_monitor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerUDP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerUDP) ProtoMessage() {}

func (x *LayerUDP) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_monitor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerUDP.ProtoReflect.Descriptor instead.
func (*LayerUDP) Descriptor() ([]byte, []int) {
	return file_pkg_pb_monitor_proto_rawDescGZIP(), []int{8}
}

func (x *LayerUDP) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *LayerUDP) GetDestPort() uint32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

func (x *LayerUDP) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *LayerUDP) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

type LayerICMPV4 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeCode      string                 `protobuf:"bytes,1,opt,name=typeCode,proto3" json:"typeCode,omitempty"`
	Checksum      uint32                 `protobuf:"varint,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Id            uint32                 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Seq           uint32                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerICMPV4) Reset() {
	*x = LayerICMPV4{}
	mi := &file_pkg_pb_monitor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerICMPV4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerICMPV4) ProtoMessage() {}

func (x *LayerICMPV4) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_monitor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerICMPV4.ProtoReflect.Descriptor instead.
func (*LayerICMPV4) Descriptor() ([]byte, []int) {
	return file_pkg_pb_monitor_proto_rawDescGZIP(), []int{9}
}

func (x *LayerICMPV4) GetTypeCode() string {
	if x != nil {
		return x.TypeCode
	}
	return ""
}

func (x *LayerICMPV4) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *LayerICMPV4) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LayerICMPV4) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type LayerICMPV6 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeCode      string                 `protobuf:"bytes,1,opt,name=typeCode,proto3" json:"typeCode,omitempty"`
	Checksum      uint32                 `protobuf:"varint,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerICMPV6) Reset() {
	*x = LayerICMPV6{}
	mi := &file_pkg_pb_monitor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerICMPV6) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerICMPV6) ProtoMessage() {}

func (x *LayerICMPV6) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_monitor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerICMPV6.ProtoReflect.Descriptor instead.
func (*LayerICMPV6) Descriptor() ([]byte, []int) {
	return file_pkg_pb_monitor_proto_rawDescGZIP(), []int{10}
}

func (x *LayerICMPV6) GetTypeCode() string {
	if x != nil {
		return x.TypeCode
	}
	return ""
}

func (x *LayerICMPV6) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

type StreamPacketsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*StreamPacketsResponse_ActivateCommand
	Response      isStreamPacketsResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPacketsResponse) Reset() {
	*x = StreamPacketsResponse{}
	mi := &file_pkg_pb_monitor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPacketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPacketsResponse) ProtoMessage() {}

func (x *StreamPacketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_monitor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPacketsResponse.ProtoReflect.Descriptor instead.
func (*StreamPacketsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_monitor_proto_rawDescGZIP(), []int{11}
}

func (x *StreamPacketsResponse) GetResponse() isStreamPacketsResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *StreamPacketsResponse) GetActivateCommand() *ActivateCommand {
	if x != nil {
		if x, ok := x.Response.(*StreamPacketsResponse_ActivateCommand); ok {
			return x.ActivateCommand
		}
	}
	return nil
}

type isStreamPacketsResponse_Response interface {
	isStreamPacketsResponse_Response()
}

type StreamPacketsResponse_ActivateCommand struct {
	ActivateCommand *ActivateCommand `protobuf:"bytes,1,opt,name=activateCommand,proto3,oneof"`
}

func (*StreamPacketsResponse_ActivateCommand) isStreamPacketsResponse_Response() {}

type ActivateCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activate      bool                   `protobuf:"varint,1,opt,name=activate,proto3" json:"activate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateCommand) Reset() {
	*x = ActivateCommand{}
	mi := &file_pkg_pb_monitor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateCommand) ProtoMessage() {}

func (x *ActivateCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_monitor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateCommand.ProtoReflect.Descriptor instead.
func (*ActivateCommand) Descriptor() ([]byte, []int) {
	return file_pkg_pb_monitor_proto_rawDescGZIP(), []int{12}
}

func (x *ActivateCommand) GetActivate() bool {
	if x != nil {
		return x.Activate
	}
	return false
}

var File_pkg_pb_monitor_proto protoreflect.FileDescriptor

const file_pkg_pb_monitor_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/pb/monitor.proto\x12\x02pb\"<\n" +
	"\x14StreamPacketsRequest\x12$\n" +
	"\apackets\x18\x01 \x03(\v2\n" +
	".pb.PacketR\apackets\"[\n" +
	"\x06Packet\x12.\n" +
	"\bmetadata\x18\x01 \x01(\v2\x12.pb.PacketMetadataR\bmetadata\x12!\n" +
	"\x06layers\x18\x02 \x03(\v2\t.pb.LayerR\x06layers\"\xdc\x01\n" +
	"\x0ePacketMetadata\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12%\n" +
	"\x0ecapture_length\x18\x03 \x01(\rR\rcaptureLength\x12\x16\n" +
	"\x06length\x18\x04 \x01(\rR\x06length\x12%\n" +
	"\x0einterface_name\x18\x05 \x01(\tR\rinterfaceName\x12\x16\n" +
	"\x06prefix\x18\x06 \x01(\tR\x06prefix\x12\x12\n" +
	"\x04hook\x18\a \x01(\tR\x04hook\"\xa5\x02\n" +
	"\x05Layer\x12/\n" +
	"\bethernet\x18\x02 \x01(\v2\x11.pb.LayerEthernetH\x00R\bethernet\x12#\n" +
	"\x04ipv4\x18\x03 \x01(\v2\r.pb.LayerIPv4H\x00R\x04ipv4\x12#\n" +
	"\x04ipv6\x18\x04 \x01(\v2\r.pb.LayerIPv6H\x00R\x04ipv6\x12 \n" +
	"\x03tcp\x18\x05 \x01(\v2\f.pb.LayerTCPH\x00R\x03tcp\x12 \n" +
	"\x03udp\x18\x06 \x01(\v2\f.pb.LayerUDPH\x00R\x03udp\x12)\n" +
	"\x06icmpv4\x18\a \x01(\v2\x0f.pb.LayerICMPV4H\x00R\x06icmpv4\x12)\n" +
	"\x06icmpv6\x18\b \x01(\v2\x0f.pb.LayerICMPV6H\x00R\x06icmpv6B\a\n" +
	"\x05layer\"a\n" +
	"\rLayerEthernet\x12\x17\n" +
	"\asrc_mac\x18\x01 \x01(\tR\x06srcMac\x12\x19\n" +
	"\bdest_mac\x18\x02 \x01(\tR\adestMac\x12\x1c\n" +
	"\tethertype\x18\x03 \x01(\tR\tethertype\"i\n" +
	"\tLayerIPv4\x12\x15\n" +
	"\x06src_ip\x18\x01 \x01(\tR\x05srcIp\x12\x17\n" +
	"\adest_ip\x18\x02 \x01(\tR\x06destIp\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\rR\x03ttl\"y\n" +
	"\tLayerIPv6\x12\x15\n" +
	"\x06src_ip\x18\x01 \x01(\tR\x05srcIp\x12\x17\n" +
	"\adest_ip\x18\x02 \x01(\tR\x06destIp\x12\x1f\n" +
	"\vnext_header\x18\x03 \x01(\tR\n" +
	"nextHeader\x12\x1b\n" +
	"\thop_limit\x18\x04 \x01(\rR\bhopLimit\"\xe2\x01\n" +
	"\bLayerTCP\x12\x19\n" +
	"\bsrc_port\x18\x01 \x01(\rR\asrcPort\x12\x1b\n" +
	"\tdest_port\x18\x02 \x01(\rR\bdestPort\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\rR\x03seq\x12\x10\n" +
	"\x03ack\x18\x04 \x01(\rR\x03ack\x12\x1f\n" +
	"\vdata_offset\x18\x05 \x01(\rR\n" +
	"dataOffset\x12\x16\n" +
	"\x06window\x18\x06 \x01(\rR\x06window\x12\x1a\n" +
	"\bchecksum\x18\a \x01(\rR\bchecksum\x12%\n" +
	"\x0eurgent_pointer\x18\b \x01(\rR\rurgentPointer\"v\n" +
	"\bLayerUDP\x12\x19\n" +
	"\bsrc_port\x18\x01 \x01(\rR\asrcPort\x12\x1b\n" +
	"\tdest_port\x18\x02 \x01(\rR\bdestPort\x12\x16\n" +
	"\x06length\x18\x03 \x01(\rR\x06length\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\rR\bchecksum\"g\n" +
	"\vLayerICMPV4\x12\x1a\n" +
	"\btypeCode\x18\x01 \x01(\tR\btypeCode\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\rR\bchecksum\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\rR\x02id\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\rR\x03seq\"E\n" +
	"\vLayerICMPV6\x12\x1a\n" +
	"\btypeCode\x18\x01 \x01(\tR\btypeCode\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\rR\bchecksum\"d\n" +
	"\x15StreamPacketsResponse\x12?\n" +
	"\x0factivateCommand\x18\x01 \x01(\v2\x13.pb.ActivateCommandH\x00R\x0factivateCommandB\n" +
	"\n" +
	"\bresponse\"-\n" +
	"\x0fActivateCommand\x12\x1a\n" +
	"\bactivate\x18\x01 \x01(\bR\bactivate2U\n" +
	"\aMonitor\x12J\n" +
	"\rStreamPackets\x12\x18.pb.StreamPacketsRequest\x1a\x19.pb.StreamPacketsResponse\"\x00(\x010\x01B,Z*github.com/schidstorm/ulogd_monitor/pkg/pbb\x06proto3"

var (
	file_pkg_pb_monitor_proto_rawDescOnce sync.Once
	file_pkg_pb_monitor_proto_rawDescData []byte
)

func file_pkg_pb_monitor_proto_rawDescGZIP() []byte {
	file_pkg_pb_monitor_proto_rawDescOnce.Do(func() {
		file_pkg_pb_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_monitor_proto_rawDesc), len(file_pkg_pb_monitor_proto_rawDesc)))
	})
	return file_pkg_pb_monitor_proto_rawDescData
}

var file_pkg_pb_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_pb_monitor_proto_goTypes = []any{
	(*StreamPacketsRequest)(nil),  // 0: pb.StreamPacketsRequest
	(*Packet)(nil),                // 1: pb.Packet
	(*PacketMetadata)(nil),        // 2: pb.PacketMetadata
	(*Layer)(nil),                 // 3: pb.Layer
	(*LayerEthernet)(nil),         // 4: pb.LayerEthernet
	(*LayerIPv4)(nil),             // 5: pb.LayerIPv4
	(*LayerIPv6)(nil),             // 6: pb.LayerIPv6
	(*LayerTCP)(nil),              // 7: pb.LayerTCP
	(*LayerUDP)(nil),              // 8: pb.LayerUDP
	(*LayerICMPV4)(nil),           // 9: pb.LayerICMPV4
	(*LayerICMPV6)(nil),           // 10: pb.LayerICMPV6
	(*StreamPacketsResponse)(nil), // 11: pb.StreamPacketsResponse
	(*ActivateCommand)(nil),       // 12: pb.ActivateCommand
}
var file_pkg_pb_monitor_proto_depIdxs = []int32{
	1,  // 0: pb.StreamPacketsRequest.packets:type_name -> pb.Packet
	2,  // 1: pb.Packet.metadata:type_name -> pb.PacketMetadata
	3,  // 2: pb.Packet.layers:type_name -> pb.Layer
	4,  // 3: pb.Layer.ethernet:type_name -> pb.LayerEthernet
	5,  // 4: pb.Layer.ipv4:type_name -> pb.LayerIPv4
	6,  // 5: pb.Layer.ipv6:type_name -> pb.LayerIPv6
	7,  // 6: pb.Layer.tcp:type_name -> pb.LayerTCP
	8,  // 7: pb.Layer.udp:type_name -> pb.LayerUDP
	9,  // 8: pb.Layer.icmpv4:type_name -> pb.LayerICMPV4
	10, // 9: pb.Layer.icmpv6:type_name -> pb.LayerICMPV6
	12, // 10: pb.StreamPacketsResponse.activateCommand:type_name -> pb.ActivateCommand
	0,  // 11: pb.Monitor.StreamPackets:input_type -> pb.StreamPacketsRequest
	11, // 12: pb.Monitor.StreamPackets:output_type -> pb.StreamPacketsResponse
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pkg_pb_monitor_proto_init() }
func file_pkg_pb_monitor_proto_init() {
	if File_pkg_pb_monitor_proto != nil {
		return
	}
	file_pkg_pb_monitor_proto_msgTypes[3].OneofWrappers = []any{
		(*Layer_Ethernet)(nil),
		(*Layer_Ipv4)(nil),
		(*Layer_Ipv6)(nil),
		(*Layer_Tcp)(nil),
		(*Layer_Udp)(nil),
		(*Layer_Icmpv4)(nil),
		(*Layer_Icmpv6)(nil),
	}
	file_pkg_pb_monitor_proto_msgTypes[11].OneofWrappers = []any{
		(*StreamPacketsResponse_ActivateCommand)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_monitor_proto_rawDesc), len(file_pkg_pb_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_monitor_proto_goTypes,
		DependencyIndexes: file_pkg_pb_monitor_proto_depIdxs,
		MessageInfos:      file_pkg_pb_monitor_proto_msgTypes,
	}.Build()
	File_pkg_pb_monitor_proto = out.File
	file_pkg_pb_monitor_proto_goTypes = nil
	file_pkg_pb_monitor_proto_depIdxs = nil
}
