// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/monitor/monitor.proto

package monitor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendPacketRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The request message containing the user's name.
	Packet        *NFLogPacket    `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
	Metadata      *PacketMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPacketRequest) Reset() {
	*x = SendPacketRequest{}
	mi := &file_pkg_monitor_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPacketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPacketRequest) ProtoMessage() {}

func (x *SendPacketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_monitor_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPacketRequest.ProtoReflect.Descriptor instead.
func (*SendPacketRequest) Descriptor() ([]byte, []int) {
	return file_pkg_monitor_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *SendPacketRequest) GetPacket() *NFLogPacket {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *SendPacketRequest) GetMetadata() *PacketMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PacketMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketMetadata) Reset() {
	*x = PacketMetadata{}
	mi := &file_pkg_monitor_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketMetadata) ProtoMessage() {}

func (x *PacketMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_monitor_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketMetadata.ProtoReflect.Descriptor instead.
func (*PacketMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_monitor_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *PacketMetadata) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

// The request message containing the user's name.
type NFLogPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Family        uint32                 `protobuf:"varint,1,opt,name=family,proto3" json:"family,omitempty"`
	Protocol      int32                  `protobuf:"varint,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	PayloadLen    int32                  `protobuf:"varint,3,opt,name=payload_len,json=payloadLen,proto3" json:"payload_len,omitempty"`
	Prefix        string                 `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Indev         string                 `protobuf:"bytes,5,opt,name=indev,proto3" json:"indev,omitempty"`
	Outdev        string                 `protobuf:"bytes,6,opt,name=outdev,proto3" json:"outdev,omitempty"`
	Network       *NFLogPacket_Network   `protobuf:"bytes,7,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NFLogPacket) Reset() {
	*x = NFLogPacket{}
	mi := &file_pkg_monitor_monitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NFLogPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NFLogPacket) ProtoMessage() {}

func (x *NFLogPacket) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_monitor_monitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NFLogPacket.ProtoReflect.Descriptor instead.
func (*NFLogPacket) Descriptor() ([]byte, []int) {
	return file_pkg_monitor_monitor_proto_rawDescGZIP(), []int{2}
}

func (x *NFLogPacket) GetFamily() uint32 {
	if x != nil {
		return x.Family
	}
	return 0
}

func (x *NFLogPacket) GetProtocol() int32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *NFLogPacket) GetPayloadLen() int32 {
	if x != nil {
		return x.PayloadLen
	}
	return 0
}

func (x *NFLogPacket) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *NFLogPacket) GetIndev() string {
	if x != nil {
		return x.Indev
	}
	return ""
}

func (x *NFLogPacket) GetOutdev() string {
	if x != nil {
		return x.Outdev
	}
	return ""
}

func (x *NFLogPacket) GetNetwork() *NFLogPacket_Network {
	if x != nil {
		return x.Network
	}
	return nil
}

type NFLogPacket_Network struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	SrcIp         []byte                         `protobuf:"bytes,1,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DestIp        []byte                         `protobuf:"bytes,2,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	Protocol      int32                          `protobuf:"varint,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Transport     *NFLogPacket_Network_Transport `protobuf:"bytes,4,opt,name=transport,proto3" json:"transport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NFLogPacket_Network) Reset() {
	*x = NFLogPacket_Network{}
	mi := &file_pkg_monitor_monitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NFLogPacket_Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NFLogPacket_Network) ProtoMessage() {}

func (x *NFLogPacket_Network) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_monitor_monitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NFLogPacket_Network.ProtoReflect.Descriptor instead.
func (*NFLogPacket_Network) Descriptor() ([]byte, []int) {
	return file_pkg_monitor_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *NFLogPacket_Network) GetSrcIp() []byte {
	if x != nil {
		return x.SrcIp
	}
	return nil
}

func (x *NFLogPacket_Network) GetDestIp() []byte {
	if x != nil {
		return x.DestIp
	}
	return nil
}

func (x *NFLogPacket_Network) GetProtocol() int32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *NFLogPacket_Network) GetTransport() *NFLogPacket_Network_Transport {
	if x != nil {
		return x.Transport
	}
	return nil
}

type NFLogPacket_Network_Transport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcPort       int32                  `protobuf:"varint,1,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DestPort      int32                  `protobuf:"varint,2,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NFLogPacket_Network_Transport) Reset() {
	*x = NFLogPacket_Network_Transport{}
	mi := &file_pkg_monitor_monitor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NFLogPacket_Network_Transport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NFLogPacket_Network_Transport) ProtoMessage() {}

func (x *NFLogPacket_Network_Transport) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_monitor_monitor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NFLogPacket_Network_Transport.ProtoReflect.Descriptor instead.
func (*NFLogPacket_Network_Transport) Descriptor() ([]byte, []int) {
	return file_pkg_monitor_monitor_proto_rawDescGZIP(), []int{4}
}

func (x *NFLogPacket_Network_Transport) GetSrcPort() int32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *NFLogPacket_Network_Transport) GetDestPort() int32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

type SendPacketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPacketResponse) Reset() {
	*x = SendPacketResponse{}
	mi := &file_pkg_monitor_monitor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPacketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPacketResponse) ProtoMessage() {}

func (x *SendPacketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_monitor_monitor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPacketResponse.ProtoReflect.Descriptor instead.
func (*SendPacketResponse) Descriptor() ([]byte, []int) {
	return file_pkg_monitor_monitor_proto_rawDescGZIP(), []int{5}
}

var File_pkg_monitor_monitor_proto protoreflect.FileDescriptor

const file_pkg_monitor_monitor_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/monitor/monitor.proto\x12\amonitor\"v\n" +
	"\x11SendPacketRequest\x12,\n" +
	"\x06packet\x18\x01 \x01(\v2\x14.monitor.NFLogPacketR\x06packet\x123\n" +
	"\bmetadata\x18\x02 \x01(\v2\x17.monitor.PacketMetadataR\bmetadata\",\n" +
	"\x0ePacketMetadata\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"\xe0\x01\n" +
	"\vNFLogPacket\x12\x16\n" +
	"\x06family\x18\x01 \x01(\rR\x06family\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\x05R\bprotocol\x12\x1f\n" +
	"\vpayload_len\x18\x03 \x01(\x05R\n" +
	"payloadLen\x12\x16\n" +
	"\x06prefix\x18\x04 \x01(\tR\x06prefix\x12\x14\n" +
	"\x05indev\x18\x05 \x01(\tR\x05indev\x12\x16\n" +
	"\x06outdev\x18\x06 \x01(\tR\x06outdev\x126\n" +
	"\anetwork\x18\a \x01(\v2\x1c.monitor.NFLogPacket_NetworkR\anetwork\"\xa7\x01\n" +
	"\x13NFLogPacket_Network\x12\x15\n" +
	"\x06src_ip\x18\x01 \x01(\fR\x05srcIp\x12\x17\n" +
	"\adest_ip\x18\x02 \x01(\fR\x06destIp\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\x05R\bprotocol\x12D\n" +
	"\ttransport\x18\x04 \x01(\v2&.monitor.NFLogPacket_Network_TransportR\ttransport\"W\n" +
	"\x1dNFLogPacket_Network_Transport\x12\x19\n" +
	"\bsrc_port\x18\x01 \x01(\x05R\asrcPort\x12\x1b\n" +
	"\tdest_port\x18\x02 \x01(\x05R\bdestPort\"\x14\n" +
	"\x12SendPacketResponse2R\n" +
	"\aMonitor\x12G\n" +
	"\n" +
	"SendPacket\x12\x1a.monitor.SendPacketRequest\x1a\x1b.monitor.SendPacketResponse\"\x00B1Z/github.com/schidstorm/ulogd_monitor/pkg/monitorb\x06proto3"

var (
	file_pkg_monitor_monitor_proto_rawDescOnce sync.Once
	file_pkg_monitor_monitor_proto_rawDescData []byte
)

func file_pkg_monitor_monitor_proto_rawDescGZIP() []byte {
	file_pkg_monitor_monitor_proto_rawDescOnce.Do(func() {
		file_pkg_monitor_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_monitor_monitor_proto_rawDesc), len(file_pkg_monitor_monitor_proto_rawDesc)))
	})
	return file_pkg_monitor_monitor_proto_rawDescData
}

var file_pkg_monitor_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_monitor_monitor_proto_goTypes = []any{
	(*SendPacketRequest)(nil),             // 0: monitor.SendPacketRequest
	(*PacketMetadata)(nil),                // 1: monitor.PacketMetadata
	(*NFLogPacket)(nil),                   // 2: monitor.NFLogPacket
	(*NFLogPacket_Network)(nil),           // 3: monitor.NFLogPacket_Network
	(*NFLogPacket_Network_Transport)(nil), // 4: monitor.NFLogPacket_Network_Transport
	(*SendPacketResponse)(nil),            // 5: monitor.SendPacketResponse
}
var file_pkg_monitor_monitor_proto_depIdxs = []int32{
	2, // 0: monitor.SendPacketRequest.packet:type_name -> monitor.NFLogPacket
	1, // 1: monitor.SendPacketRequest.metadata:type_name -> monitor.PacketMetadata
	3, // 2: monitor.NFLogPacket.network:type_name -> monitor.NFLogPacket_Network
	4, // 3: monitor.NFLogPacket_Network.transport:type_name -> monitor.NFLogPacket_Network_Transport
	0, // 4: monitor.Monitor.SendPacket:input_type -> monitor.SendPacketRequest
	5, // 5: monitor.Monitor.SendPacket:output_type -> monitor.SendPacketResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_monitor_monitor_proto_init() }
func file_pkg_monitor_monitor_proto_init() {
	if File_pkg_monitor_monitor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_monitor_monitor_proto_rawDesc), len(file_pkg_monitor_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_monitor_monitor_proto_goTypes,
		DependencyIndexes: file_pkg_monitor_monitor_proto_depIdxs,
		MessageInfos:      file_pkg_monitor_monitor_proto_msgTypes,
	}.Build()
	File_pkg_monitor_monitor_proto = out.File
	file_pkg_monitor_monitor_proto_goTypes = nil
	file_pkg_monitor_monitor_proto_depIdxs = nil
}
